name: very_good_flame_game
description: A Very Good Flame Game created by Very Good Ventures.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^5.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: 1.8.2
  flame_audio: ^2.0.5
  flame_behaviors: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  intl: ^0.18.0
  mockingjay: ^0.4.0

dev_dependencies:
  bloc_test: ^9.1.2
  flame_test: ^1.10.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
