name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  audioplayers: ^1.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  flame: ^1.4.0
  flame_audio: ^1.3.2
  flame_behaviors: ^0.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  intl: ^0.17.0
  mockingjay: ^0.3.0

dev_dependencies:
  bloc_test: ^9.1.0
  flame_test: ^1.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/